<?php

namespace Database\DBMS\map;

use \RelationMap;
use \TableMap;


/**
 * This class defines the structure of the 'net_bazzline_identification_service_identities' table.
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Sun Apr 20 20:56:09 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator..map
 */
class IdentityTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = '.map.IdentityTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('net_bazzline_identification_service_identities');
        $this->setPhpName('Identity');
        $this->setClassname('Database\\DBMS\\Identity');
        $this->setPackage('');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('id', 'Id', 'CHAR', true, 36, null);
        $this->addColumn('name', 'Name', 'VARCHAR', true, 40, null);
        $this->addColumn('password', 'Password', 'CHAR', true, 40, null);
        $this->addForeignKey('user_id', 'UserId', 'CHAR', 'net_bazzline_identification_service_users', 'id', true, 36, null);
        $this->addColumn('created_at', 'CreatedAt', 'DATE', true, 40, null);
        $this->addColumn('updated_at', 'UpdatedAt', 'DATE', true, 40, null);
        $this->addColumn('valid_until', 'ValidUntil', 'DATE', true, 40, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('User', 'Database\\DBMS\\User', RelationMap::MANY_TO_ONE, array('user_id' => 'id', ), null, null);
    } // buildRelations()

} // IdentityTableMap
