<?php

namespace Application\Database\DBMS;

use Application\Database\DBMS\om\BaseIdentityQuery;


/**
 * Skeleton subclass for performing query and update operations on the 'net_bazzline_identification_service_identities' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Sat Apr 19 23:07:25 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.
 */
class IdentityQuery extends BaseIdentityQuery
{
}
