<?php

namespace Database;

use Database\om\BaseUserQuery;


/**
 * Skeleton subclass for performing query and update operations on the 'net_bazzline_identification_service_users' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.1 on:
 *
 * Fri Apr 18 23:11:23 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.
 */
class UserQuery extends BaseUserQuery
{
}
